/*
The sequence of triangle numbers can be generated by adding the natural numbers. So the 7th triangle numbers would be [1 + 2 + 3 + 4 + 5 + 6 + 7 = 28]. The first ten terms would be: [1, 3, 6, 10, 15, 21, 28, 36, 45, 55, .....]
Let us list the factors of the first seven triangle numbers: 
    1 : 1
    3 : 1, 3
    6 : 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over 500 divisors ?  
*/

#include<iostream>
#include<math.h>
using namespace std;

void triangleDivisors() {

    long long tri;
    long long d = 0;
    long long n = 1;

    while (d < 500) {
        // calculate triangle number
        tri = ((n * (n+1)) / 2);
        n++;
        // count divisors (upto root of triangle number)
        d = 0;
        for (int i=1; i<=sqrt(tri); i++) {
            if (tri % i == 0) {d += 2;}         // [note: divisors come in pairs]
        }
        if (d >= 500) {cout << "Found --> " << tri;}
    }

}

int main() {

    triangleDivisors();

    return 0;

}


