// Each new term in fibonacci Sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms are 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. By considering the terms in the Fibonacci Sequence whose value does not exceed 4 million, find the sum of all even-valued terms.

#include<iostream>
using namespace std;

int main() {

    long long sum = 0;
    long long a = 1, b = 2;  // we need only even fibonacci numbers sum so we can skip first no.

    while (a < 4000000) {
        if (a % 2 == 0) {
            sum += a;
        }
        // cout << a << '\n';
        int temp = a;
        a = b;
        b = temp + b;
    }

    cout << "The sum of even-valued fibonacci series till 4 mil = " << sum;

    return 0;
}